using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations.Design;

namespace EntityFrameworkMigrationExtensions.Generators
{
    public class ExtendCSharpMigrationCodeGenerator : CSharpMigrationCodeGenerator
    {
        protected override void WriteClassStart(
            string @namespace,
            string className,
            System.Data.Entity.Migrations.Utilities.IndentedTextWriter writer,
            string @base,
            bool designer = false,
            IEnumerable<string> namespaces = null)
        {
            writer.WriteLine("// Generated Time: {0}", DateTime.Now);
            writer.WriteLine("// Generated By: {0}", Environment.UserName);
            writer.WriteLine();
            base.WriteClassStart(@namespace, className, writer, @base, designer, namespaces);
        }
    }
}
